### ISSUE TITLE
Tokenizer english or dutch

### ISSUE THREAD

**Issue by erwin314** [iPieter/RobBERT#6]
When downloading the pretrained Roberta Tokenizer and inspecting the merges.txt and vocab.json, they seem to be *English*. I was expecting *Dutch*.

Are the files correct? or is the download or my expectation wrong?

To download and inspect use:
```python
tokenizer = RobertaTokenizer.from_pretrained("pdelobelle/robBERT-base")
tokenizer.save_vocabulary("/somefolder")
```

**Comment by twinters** [comment]
Hi Erwin,

These files are correct.

RobBERT was trained using the default [Fairseq RoBERTa](https://github.com/pytorch/fairseq/tree/master/examples/roberta) tokenizer, which is indeed an English tokenizer. We assume that the fact that the model still performs really well stems from the fact that Dutch and English are quite closely related languages.
As mentioned in the future work section of our [paper](https://arxiv.org/abs/2001.06286), we are currently looking into changing and improving the tokenizer in a future version using the new [tokenizers](https://github.com/huggingface/tokenizers) repository that HuggingFace recently released.

Hope this helps!

**Comment by iPieter** [comment]
As @twinters already commented, those files are indeed correct. 

It's interesting that we do achieve SOTA results, even on task with typical Dutch tokens (die/dat). This is likely due to Dutch and English sharing the same Latin script, being closely related languages, and borrowing a lot of words. When looking at GPT-2—which also uses BPE tokenization—a similar phenomena can be observed for Dutch (even without finetuning, which you can try at [HuggingFace's demo](https://transformer.huggingface.co/doc/gpt2-large)).

Given this, we've released our first version with Fairseq's standard tokenization and are planning to release a second version, as well as an in-depth discussion about the effects of the tokenization.

Since the files are correct, I'm closing this issue.

**Comment by erwin314** [comment]
Hi Thomas, Thanks for your help! I had the pleasure of reading your paper a while back. Seems I missed the mention about this in the future work section.

Looking forward to the next version. Including dutch tokens and Unicode glyphs should give some improvements.

**Comment by erwin314** [comment]
and thank you Pieter. As I said, looking forward to reading the next version.
